name: Flask App CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flask
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 app

      - name: Start Flask app
        run: |
          cd app
          python __init__.py &
          sleep 5

      - name: Test endpoint
        run: |
          curl http://localhost:5000/hello
          curl http://localhost:5000/health
